//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Homework.Remote.Service.RemoteSearchService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RemoteSearchService.ISearcher")]
    public interface ISearcher {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearcher/QueryCommodityPage", ReplyAction="http://tempuri.org/ISearcher/QueryCommodityPageResponse")]
        string QueryCommodityPage(int pageIndex, int pageSize, string keyword, int[] categoryIdList, string priceFilter, string priceOrderBy);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearcher/QueryCommodityPage", ReplyAction="http://tempuri.org/ISearcher/QueryCommodityPageResponse")]
        System.Threading.Tasks.Task<string> QueryCommodityPageAsync(int pageIndex, int pageSize, string keyword, int[] categoryIdList, string priceFilter, string priceOrderBy);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISearcherChannel : Homework.Remote.Service.RemoteSearchService.ISearcher, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearcherClient : System.ServiceModel.ClientBase<Homework.Remote.Service.RemoteSearchService.ISearcher>, Homework.Remote.Service.RemoteSearchService.ISearcher {
        
        public SearcherClient() {
        }
        
        public SearcherClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SearcherClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearcherClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearcherClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string QueryCommodityPage(int pageIndex, int pageSize, string keyword, int[] categoryIdList, string priceFilter, string priceOrderBy) {
            return base.Channel.QueryCommodityPage(pageIndex, pageSize, keyword, categoryIdList, priceFilter, priceOrderBy);
        }
        
        public System.Threading.Tasks.Task<string> QueryCommodityPageAsync(int pageIndex, int pageSize, string keyword, int[] categoryIdList, string priceFilter, string priceOrderBy) {
            return base.Channel.QueryCommodityPageAsync(pageIndex, pageSize, keyword, categoryIdList, priceFilter, priceOrderBy);
        }
    }
}
